# Generated by Django 6.0.5 on 2026-05-15 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(blank=True, null=True)),
                ('active_ingredient', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('nafdac_reg_no', models.TextField(blank=True, null=True, unique=True)),
                ('form', models.TextField(blank=True, null=True)),
                ('applicant', models.TextField(blank=True, null=True)),
                ('approval_date', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drugs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrn_queried', models.CharField(blank=True, max_length=50, null=True)),
                ('name_queried', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=30)),
                ('source', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('geolocation', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verification_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
